// core/smtp.mjs is the one hand-rolled network protocol in this codebase
// with no format fixture to round-trip against -- these tests run a small
// scripted SMTP server over a real socket and inspect exactly what the
// client sent, the way the plan called for.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import net from 'node:net';
import tls from 'node:tls';
import { sendMail, SmtpError } from '../src/core/smtp.mjs';

// A throwaway self-signed cert for CN=127.0.0.1, valid 10 years from
// generation, committed as static test data rather than generated by
// shelling out to openssl at test time -- this project runs its test suite
// with nothing beyond the Node runtime itself, and that includes the tests.
const TEST_CERT = `-----BEGIN CERTIFICATE-----
MIIDCTCCAfGgAwIBAgIUcwyjKs5W3Xus+CRlbdB7HUxLGoIwDQYJKoZIhvcNAQEL
BQAwFDESMBAGA1UEAwwJMTI3LjAuMC4xMB4XDTI2MDkyNDE3MDgxM1oXDTM2MDky
MTE3MDgxM1owFDESMBAGA1UEAwwJMTI3LjAuMC4xMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAzdShjl6PRCtmDK13okW1nEmlDf3dAPg5YLkRky71uk7x
5EqeG7VsRlgzQr0zhNcu5DNfX0eUc9dGPBd818ti30qz6WGYR3llsiLYh07D1q3F
Yvqh+76wMf3/AvGbl8RhY+jhgmEbn4apo2OnEgA/El0mJn/Ad9aXQgb+2w+olOnV
qe392x2JgPxNJu3NPiiq0sdkKwsOP/IO0XsIhp2czLLLZp9dC5RqRdSP31ba9p7j
b+nSD//QLat0JEPfVbYvSAX2iU+edPJIqmgBGLvJiANYPTBkvKupBrcmlxBz6ejb
G1O/SIxujAfXmPhru0h3CgjnCOh1hFTTLjhxZL6U6wIDAQABo1MwUTAdBgNVHQ4E
FgQUWQNUMDlRyVSSQrL4CfcGCUzt2jkwHwYDVR0jBBgwFoAUWQNUMDlRyVSSQrL4
CfcGCUzt2jkwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAEcke
eDf7zQf5e9Jy7UGKELsQW2dNDlnRUyUcZMrxvwUlWVv/8vKAUAboJ0SCuy9s44d+
bjBYUZrymO8C/NpGBd+3hMRGoLfKzoGZvlElRvXIb1Ii72w4vmxW2fT/dwYZlGJw
eKpwbcurNrDt9APFkcMUyxcm4SQ7EqUjDvj325394rqbB4fq8SGOb5d2XlPsCreo
Pijh/e9YdqMEgfT5t6SMoqXvJTWiyadIp2+OfnKLJLuK4KLTzs2dLabJoZs572Tr
yHlrXTnbJXasHrLYUnrF81au2Ihe8Q9mGwvL/Js7MS2K/UzXRfSVxvYN1y1hT1mB
SnlWTeA+QwZd+EPcRA==
-----END CERTIFICATE-----`;
const TEST_KEY = `-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDN1KGOXo9EK2YM
rXeiRbWcSaUN/d0A+DlguRGTLvW6TvHkSp4btWxGWDNCvTOE1y7kM19fR5Rz10Y8
F3zXy2LfSrPpYZhHeWWyItiHTsPWrcVi+qH7vrAx/f8C8ZuXxGFj6OGCYRufhqmj
Y6cSAD8SXSYmf8B31pdCBv7bD6iU6dWp7f3bHYmA/E0m7c0+KKrSx2QrCw4/8g7R
ewiGnZzMsstmn10LlGpF1I/fVtr2nuNv6dIP/9Atq3QkQ99Vti9IBfaJT5508kiq
aAEYu8mIA1g9MGS8q6kGtyaXEHPp6NsbU79IjG6MB9eY+Gu7SHcKCOcI6HWEVNMu
OHFkvpTrAgMBAAECggEAC/+7xU1s46f2BIIuSbbvneNLLHQiqJZP3fwb8q0XpRtK
Dalt6yaZ38XvgxH9iV5z/Nij1C2bkV842HL0E65nHqY/s7i9RFlm3MocPlMQppit
u5Xp0H+uzNNGRPkpvWC03rqqPswDbLrQc9Zw3GNISf1FJpRm93V6jt5SiBmzFa8r
PuLEGb4dYjPw1NG7BxxO+ToI7ceSbjcslv/qbO2DZGBFtxoAd7E7VZbdJ/A6CiUN
zST83hiD+NjGfaEnC2y4X4xhSukB6UhSnfzAjxs4pEiy/+rMJUbVL7nO7ibrabEB
sOCZdspuuBWdaV3iuA/0sPOsRN2I+dDXX1gKvgWRZQKBgQDtJgE8gGDhJhAv1yLu
XYn61RSkFlmD/D4OuImGutslwd2dI3sdz6guD985IRjN0/NSkPDm+Y6PM+lbHlqK
Otos3RW6PNspIHmQoQMZ0V3lCNgle+I+narLpipVdXbcsHcp43AzZgn0zuzhwOix
Oen6IPbn7q0RCqhSMeNp81BBDQKBgQDeMU3zI9gFgcxRQhXck4oTwxENWi39zHUP
dsCyjdDZne95jZJeR14cmHH9InWI1r67xo/8EX3hTIdX8vBbQ66xWtb8DZURtGjp
d4/zyPkQYs1NcxaYkGFsmb2njly+e6cBEJpz1i/0sf5IGKLeueCy7JjmcPxQ61Rx
shgdLrz/1wKBgQDGaIiaRNJJLN5YGEeaZFofqQy26BgGrBCDonM1bLoTEerHILtN
ysHrn83j70PgWRb3mlpi9KIIP6daW7/mbKzC4kneYjH+a7Qpg/yjKh7Dk627VrWI
K8OM1L4Qd9F1fJKGUko6RoHH9yQLEKneNRUD93Z7v52+Z0tCUYjxyOb5NQKBgCES
n7KwRChVsK7rsktZ3rSgVXpyUOQ1ObtqhrZNK6govQuPyhikcNq6ykTOi0YqCMv0
e1we0mjltkOeEq7S/T7C8bsk3mp7Ox59QH0eDgylWD/OALAG1amPnM5C/4UO7MXY
zdSuLgczM1FR8XRLoKmhVAUBDl2RGcmuo648Vb+TAoGBALJXkBbONkCW9Kh13F1e
Yq227NzuR7mDBhVgIAnYhkXv9T1MqqeAxkiUjaUplciT7nBdl4gbmsYQ2a4F9c9W
C6i62BY5sHqgGFXyN1elB4S4nooMqVLIHfkR4bADlVuEPIZYKDwuKupMpe0kN25N
7mJm9YgKT35VHtkfITp6wln+
-----END PRIVATE KEY-----`;

/** A scripted plain-text SMTP server: `script` maps a command's first word
 * (case-insensitive) to the reply lines to send back. Every unmatched
 * command gets a generic 250. Records every line the client sent, plus the
 * full DATA body as one entry. */
function fakeServer(script = {}) {
  const received = [];
  const server = net.createServer((socket) => {
    socket.on('error', () => {}); // the client destroys its socket once done; that is not a test failure
    socket.write('220 fake.smtp ready\r\n');
    let buf = '', dataBuf = '', inData = false;
    socket.on('data', (chunk) => {
      buf += chunk.toString('latin1');
      let idx;
      while ((idx = buf.indexOf('\r\n')) !== -1) {
        const line = buf.slice(0, idx);
        buf = buf.slice(idx + 2);
        if (inData) {
          if (line === '.') { inData = false; received.push({ data: dataBuf }); socket.write('250 2.0.0 OK\r\n'); continue; }
          dataBuf += (dataBuf ? '\r\n' : '') + line;
          continue;
        }
        received.push(line);
        const word = line.split(/\s/)[0].toUpperCase();
        if (word === 'DATA') { dataBuf = ''; inData = true; socket.write((script.DATA || ['354 go ahead']).join('\r\n') + '\r\n'); continue; }
        const reply = script[word];
        socket.write((typeof reply === 'function' ? reply(line) : reply || ['250 OK']).join('\r\n') + '\r\n');
      }
    });
  });
  return { server, received: () => received };
}

/** A real TLS server (implicit TLS, as port 465 is) running a scripted
 * AUTH LOGIN + MAIL/RCPT/DATA exchange, step-driven since the base64
 * username/password lines have no command word of their own to script by. */
function fakeTlsAuthServer({ authReply = ['235 2.7.0 Authenticated'] } = {}) {
  const server = tls.createServer({ cert: TEST_CERT, key: TEST_KEY });
  server.on('secureConnection', (socket) => {
    socket.on('error', () => {});
    socket.write('220 fake.smtps ready\r\n');
    let buf = '', step = 0, dataBuf = '', inData = false;
    socket.on('data', (chunk) => {
      buf += chunk.toString('latin1');
      let idx;
      while ((idx = buf.indexOf('\r\n')) !== -1) {
        const line = buf.slice(0, idx); buf = buf.slice(idx + 2);
        if (inData) {
          if (line === '.') { inData = false; socket.write('250 2.0.0 OK\r\n'); continue; }
          dataBuf += (dataBuf ? '\r\n' : '') + line; continue;
        }
        if (/^EHLO/i.test(line)) socket.write('250-fake.smtps\r\n250 AUTH LOGIN\r\n');
        else if (/^AUTH LOGIN/i.test(line)) { step = 1; socket.write('334 VXNlcm5hbWU6\r\n'); }
        else if (step === 1) { step = 2; socket.write('334 UGFzc3dvcmQ6\r\n'); }
        else if (step === 2) { step = 0; socket.write(authReply.join('\r\n') + '\r\n'); }
        else if (/^MAIL FROM/i.test(line)) socket.write('250 OK\r\n');
        else if (/^RCPT TO/i.test(line)) socket.write('250 OK\r\n');
        else if (/^DATA/i.test(line)) { dataBuf = ''; inData = true; socket.write('354 go\r\n'); }
        else if (/^QUIT/i.test(line)) socket.write('221 bye\r\n');
        else socket.write('250 OK\r\n');
      }
    });
  });
  return server;
}

async function listen(server) {
  await new Promise((r) => server.listen(0, '127.0.0.1', r));
  return server.address().port;
}

test('a plain send with no auth follows MAIL/RCPT/DATA and stuffs the body correctly', async () => {
  const { server, received } = fakeServer({
    EHLO: ['250 fake.smtp'], // no STARTTLS, no AUTH offered -- an open relay for internal use
  });
  const port = await listen(server);
  try {
    await sendMail({ host: '127.0.0.1', port, secure: false, timeoutMs: 2000 }, {
      from: 'meridian@example.test', to: 'ap@customer.test', subject: 'Statement',
      text: 'Line one\n.\nLine three, a line that is only a dot above must survive.',
    });
    const cmds = received();
    assert.ok(cmds.some((c) => typeof c === 'string' && /^EHLO/i.test(c)));
    assert.ok(cmds.some((c) => c === 'MAIL FROM:<meridian@example.test>'));
    assert.ok(cmds.some((c) => c === 'RCPT TO:<ap@customer.test>'));
    const dataEntry = cmds.find((c) => c && typeof c === 'object' && 'data' in c);
    assert.ok(dataEntry, 'the message body must have been sent');
    // The lone "." line must have arrived stuffed as ".." and only be
    // unstuffed back to "." by the receiver -- if dot-stuffing were
    // missing, the real DATA phase would have ended right after "Line one".
    assert.ok(dataEntry.data.includes('Line three, a line that is only a dot above must survive.'),
      'a lone "." mid-message must not have been read as the end of DATA');
    assert.match(dataEntry.data, /Subject: Statement/);
  } finally {
    server.close();
  }
});

test('AUTH LOGIN over implicit TLS sends the real base64 username and password', async () => {
  const server = fakeTlsAuthServer();
  const port = await listen(server);
  try {
    await sendMail(
      { host: '127.0.0.1', port, secure: true, timeoutMs: 2000, rejectUnauthorized: false, username: 'bot@example.test', password: 'hunter2 secret' },
      { from: 'a@example.test', to: 'b@example.test', subject: 'Hi', text: 'hi' },
    );
  } finally {
    server.close();
  }
});

test('a bad password over implicit TLS surfaces as a clear SmtpError, not a hang', async () => {
  const server = fakeTlsAuthServer({ authReply: ['535 5.7.8 Authentication failed'] });
  const port = await listen(server);
  try {
    await assert.rejects(
      () => sendMail(
        { host: '127.0.0.1', port, secure: true, timeoutMs: 2000, rejectUnauthorized: false, username: 'bot@example.test', password: 'wrong' },
        { from: 'a@example.test', to: 'b@example.test', subject: 'Hi', text: 'hi' },
      ),
      (err) => { assert.ok(err instanceof SmtpError); assert.match(err.message, /535/); return true; },
    );
  } finally {
    server.close();
  }
});

test('a rejected recipient surfaces as a clear SmtpError, not a hang', async () => {
  const { server } = fakeServer({
    EHLO: ['250 fake.smtp'],
    RCPT: () => ['550 5.1.1 No such user'],
  });
  const port = await listen(server);
  try {
    await assert.rejects(
      () => sendMail({ host: '127.0.0.1', port, secure: false, timeoutMs: 2000 },
        { from: 'a@example.test', to: 'nobody@example.test', subject: 'Hi', text: 'hi' }),
      (err) => { assert.ok(err instanceof SmtpError); assert.match(err.message, /550/); return true; },
    );
  } finally {
    server.close();
  }
});

test('credentials are never sent in the clear when the server offers no STARTTLS', async () => {
  const { server, received } = fakeServer({
    EHLO: ['250 fake.smtp'], // deliberately no STARTTLS and no AUTH advertised
  });
  const port = await listen(server);
  try {
    await assert.rejects(
      () => sendMail({ host: '127.0.0.1', port, secure: false, timeoutMs: 2000, username: 'bot@example.test', password: 'hunter2' },
        { from: 'a@example.test', to: 'b@example.test', subject: 'Hi', text: 'hi' }),
      (err) => { assert.ok(err instanceof SmtpError); assert.equal(err.code, 'INSECURE_AUTH'); return true; },
    );
    assert.ok(!received().some((c) => typeof c === 'string' && /^AUTH/i.test(c)),
      'no AUTH command may reach the wire once the refusal fires');
  } finally {
    server.close();
  }
});

test('a STARTTLS upgrade is actually attempted, not merely trusted from the 220', async () => {
  // This fake server answers STARTTLS with 220 but is not a TLS endpoint --
  // if the client trusted that 220 and kept talking plaintext SMTP, the
  // next command (EHLO) would get a real reply and the send would proceed.
  // Since it does not (the TLS handshake itself fails against a non-TLS
  // peer), this proves the upgrade is real, not skipped.
  const { server } = fakeServer({
    EHLO: ['250-fake.smtp', '250 STARTTLS'],
    STARTTLS: ['220 Go ahead'],
  });
  const port = await listen(server);
  try {
    await assert.rejects(() => sendMail(
      { host: '127.0.0.1', port, secure: false, timeoutMs: 1500 },
      { from: 'a@example.test', to: 'b@example.test', subject: 'Hi', text: 'hi' },
    ));
  } finally {
    server.close();
  }
});

test('an attachment is base64-encoded and decodes back to the exact original bytes', async () => {
  const { server, received } = fakeServer({ EHLO: ['250 fake.smtp'] });
  const port = await listen(server);
  const original = Buffer.from('%PDF-1.4 pretend pdf bytes, including a line that starts with a dot:\n.oops\nend');
  try {
    await sendMail({ host: '127.0.0.1', port, secure: false, timeoutMs: 2000 }, {
      from: 'a@example.test', to: 'b@example.test', subject: 'Statement',
      text: 'See attached.',
      attachments: [{ filename: 'statement.pdf', contentType: 'application/pdf', bytes: original }],
    });
    const dataEntry = received().find((c) => c && typeof c === 'object' && 'data' in c);
    assert.match(dataEntry.data, /Content-Type: multipart\/mixed; boundary="/);
    assert.match(dataEntry.data, /Content-Disposition: attachment; filename="statement\.pdf"/);
    const b64 = /Content-Disposition: attachment; filename="statement\.pdf"\r?\n\r?\n([\s\S]+?)\r?\n\r?\n--/.exec(dataEntry.data)?.[1];
    assert.ok(b64, 'the base64 attachment body must be present between its headers and the next boundary');
    const decoded = Buffer.from(b64.replace(/\r?\n/g, ''), 'base64');
    assert.ok(decoded.equals(original), 'the attachment must decode back to exactly the original bytes');
  } finally {
    server.close();
  }
});
