// Meridian ERP :: scripts/fonts
// Fetch the typefaces the interface offers and write them into src/web/fonts.
//
// Meridian ships with no network. A font served from somebody else's CDN is a
// blank screen on an aeroplane, a third party watching who opens the books,
// and a dependency that can be withdrawn -- so the files live in the build and
// are served by the same server as everything else.
//
// This script exists so that "where did these binaries come from" has an
// answer in the repository rather than in somebody's memory. It is not run at
// install time or build time; it is run when the set of offered typefaces
// changes, and the result is committed.
//
//   node scripts/fonts.mjs
//
// Every family here is licensed under the SIL Open Font License 1.1, which
// permits redistribution inside an application. OFL.txt is written alongside.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const HERE = path.dirname(url.fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '..', 'src', 'web', 'fonts');

// A modern browser UA, or Google Fonts serves the truetype fallback stylesheet.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

// Only the subsets a Latin-script business application actually renders. The
// Cyrillic, Greek and Vietnamese cuts would triple the payload to cover text
// no screen in this product produces.
const SUBSETS = new Set(['latin', 'latin-ext']);

const FAMILIES = [
  { family: 'IBM Plex Sans', weights: [400, 500, 600], slug: 'plex-sans' },
  { family: 'IBM Plex Mono', weights: [400, 500], slug: 'plex-mono' },
  { family: 'IBM Plex Serif', weights: [600], slug: 'plex-serif' },
  { family: 'Source Sans 3', weights: [400, 500, 600], slug: 'source-sans' },
  { family: 'JetBrains Mono', weights: [400, 500], slug: 'jetbrains-mono' },
  { family: 'Inter', weights: [400, 500, 600], slug: 'inter' },
];

const log = (...a) => console.log('·', ...a);

async function cssFor({ family, weights }) {
  const spec = `${family.replace(/ /g, '+')}:wght@${weights.join(';')}`;
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`, {
    headers: { 'User-Agent': UA },
  });
  if (!res.ok) throw new Error(`${family}: stylesheet ${res.status}`);
  return res.text();
}

/** Split a Google Fonts stylesheet into { subset, weight, url } records. */
function parseFaces(css) {
  const out = [];
  // Each @font-face is preceded by a /* subset */ comment naming its cut.
  const parts = css.split(/\/\*\s*([a-z-]+)\s*\*\//i).slice(1);
  for (let i = 0; i < parts.length; i += 2) {
    const subset = parts[i];
    const block = parts[i + 1] || '';
    const weight = Number(/font-weight:\s*(\d+)/.exec(block)?.[1] || 400);
    const href = /src:\s*url\(([^)]+)\)/.exec(block)?.[1];
    const style = /font-style:\s*(\w+)/.exec(block)?.[1] || 'normal';
    if (href && style === 'normal') out.push({ subset, weight, url: href });
  }
  return out;
}

async function main() {
  fs.mkdirSync(OUT, { recursive: true });
  const faces = [];
  let bytes = 0;

  for (const entry of FAMILIES) {
    const css = await cssFor(entry);
    const wanted = parseFaces(css).filter((f) => SUBSETS.has(f.subset));
    if (!wanted.length) throw new Error(`${entry.family}: no Latin subset in the stylesheet`);
    for (const face of wanted) {
      const name = `${entry.slug}-${face.weight}-${face.subset}.woff2`;
      const res = await fetch(face.url, { headers: { 'User-Agent': UA } });
      if (!res.ok) throw new Error(`${name}: ${res.status}`);
      const buf = Buffer.from(await res.arrayBuffer());
      fs.writeFileSync(path.join(OUT, name), buf);
      bytes += buf.length;
      faces.push({ ...face, family: entry.family, file: name, unicodeRange: unicodeRangeFor(css, face) });
      log(`${name}  ${(buf.length / 1024).toFixed(1)} KB`);
    }
  }

  fs.writeFileSync(path.join(OUT, 'fonts.css'), stylesheet(faces));
  fs.writeFileSync(path.join(OUT, 'OFL.txt'), LICENCE);
  log(`\n${faces.length} files, ${(bytes / 1024).toFixed(0)} KB total`);
  log('wrote fonts.css and OFL.txt');
}

function unicodeRangeFor(css, face) {
  // The range belongs to the block the URL came from, so find it by the URL.
  const idx = css.indexOf(face.url);
  const after = css.slice(idx, idx + 600);
  return /unicode-range:\s*([^;]+);/.exec(after)?.[1]?.trim() || null;
}

function stylesheet(faces) {
  const head = `/* Meridian ERP -- bundled typefaces.
   Generated by scripts/fonts.mjs. Do not edit by hand.

   Every family here is SIL Open Font License 1.1; see OFL.txt.
   All six are declared, but a browser only downloads the faces a page
   actually uses, so a reader who never leaves the default typeface pays for
   one family rather than six. */\n\n`;
  const blocks = faces.map((f) => [
    '@font-face {',
    `  font-family: '${f.family}';`,
    '  font-style: normal;',
    `  font-weight: ${f.weight};`,
    '  font-display: swap;',
    `  src: url('/fonts/${f.file}') format('woff2');`,
    f.unicodeRange ? `  unicode-range: ${f.unicodeRange};` : null,
    '}',
  ].filter(Boolean).join('\n'));
  return head + blocks.join('\n\n') + '\n';
}

const LICENCE = `The typefaces in this directory are distributed under the
SIL Open Font License, Version 1.1.

  IBM Plex Sans, IBM Plex Mono, IBM Plex Serif  (c) IBM Corp.
  Source Sans 3                                 (c) Adobe
  JetBrains Mono                                (c) JetBrains s.r.o.
  Inter                                         (c) The Inter Project Authors

The full licence text is available at https://openfontlicense.org and is
reproduced in each project's own repository. In summary, the OFL permits the
fonts to be used, studied, modified and redistributed freely, including
bundled inside an application such as this one, provided they are not sold by
themselves and any modified version is not released under the reserved font
names above.

These files are unmodified subsets (Latin and Latin Extended) of the released
versions, produced by the Google Fonts service.
`;

main().catch((e) => { console.error('!', e.message); process.exit(1); });
